spring.datasource:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/order_microservice
  username: headly
  password: 3669

mybatis:
  mapper-locations: classpath*:static/mapper/*.xml
spring:
  flyway:
    enabled: true
    locations: db/migration

value:
  timeout:
    minutes: 60

server:
  port: 8080