CREATE SEQUENCE SESSION_SEQ START WITH 1000 INCREMENT BY 1;
-- SESSION
CREATE TABLE session (
                         ID INTEGER,
                         SESSION_ID VARCHAR(24),
                         START_TIME DATE,
                         TIMEOUT_MINUTES INTEGER);
ALTER TABLE session ADD CONSTRAINT SESSION_ID_PK PRIMARY KEY (ID);
CREATE INDEX SESSION_PK_IDX ON "order"(ID);